
import 'dart:convert';

EditProfileModel editProfileModelFromJson(String str) => EditProfileModel.fromJson(json.decode(str));

String editProfileModelToJson(EditProfileModel data) => json.encode(data.toJson());

class EditProfileModel {
    EditProfileModel({
        required this.output,
        required this.message,
        required this.status,
    });

    List<Output> output;
    String message;
    String status;

    factory EditProfileModel.fromJson(Map<dynamic, dynamic> json) => EditProfileModel(
        output: List<Output>.from(json["output"].map((x) => Output.fromJson(x))),
        message: json["message"],
        status: json["status"],
    );

    Map<dynamic, dynamic> toJson() => {
        "output": List<dynamic>.from(output.map((x) => x.toJson())),
        "message": message,
        "status": status,
    };
}

class Output {
    Output({
        required this.cityCode,
        required this.anniversarydate,
        required this.worklocid,
        required this.patchName,
        required this.orgName,
        required this.gender,
        required this.facilityName,
        required this.bankid,
        required this.cast,
        required this.distlgdcode,
        required this.motherName,
        required this.imagePath,
        required this.username,
        required this.id,
        required this.pincode,
        required this.laBdetails,
        required this.suborgwisedesgid,
        required this.perMobile,
        required this.avgPatient,
        required this.attchHospitalName,
        required this.isaspirant,
        required this.bloodgroup,
        required this.gplgdcode,
        required this.dob,
        required this.bCompany,
        required this.workLocationName,
        required this.labIncharge,
        required this.projectName,
        required this.bankaddress,
        required this.liName,
        required this.liDocname,
        required this.pancard,
        required this.omtcscid,
        required this.yearofpassing,
        required this.centerId,
        required this.liContact,
        required this.designation,
        required this.maritialstatusId,
        required this.firstName,
        required this.educdtlid,
        required this.interestinfranch,
        required this.desglevelid,
        required this.ifsccode,
        required this.spouseName,
        required this.religion,
        required this.labContact,
        required this.orgId,
        required this.joiningdate,
        required this.fatherName,
        required this.aadhar,
        required this.tallgdcode,
        required this.mapDistCode,
        required this.ipaddress,
        required this.desgid,
        required this.bMobile,
        required this.cAddress,
        required this.bAddress,
        required this.percentage,
        required this.branchname,
        required this.maritialstatus,
        required this.liMobno,
        required this.typename,
        required this.pAddress,
        required this.cityName,
        required this.qualification,
        required this.centerName,
        required this.typeofsetup,
        required this.voterId,
        required this.edu,
        required this.district,
        required this.accountno,
        required this.typeid,
        required this.name,
        required this.lastName,
        required this.categoryId,
        required this.avgTest,
        required this.state,
        required this.statelgdcode,
        required this.labAddress,
        required this.universityname,
        required this.hlldistrictid,
        required this.facilityId,
        required this.perEmail,
        required this.subOrgId,
        required this.children,
        required this.age,
        required this.subOrgName,
        required this.bEmail,
        required this.patchCode,
        required this.projectId,
        required this.maplabCode,
        required this.middleName,
        required this.empCode,
        required this.labName,
        required this.taluka,
        required this.passbook,
        required this.bankname,
        required this.bloodid,
        required this.category,
    });

    int cityCode;
    String anniversarydate;
    int worklocid;
    String patchName;
    String orgName;
    int gender;
    String facilityName;
    int bankid;
    String cast;
    int distlgdcode;
    String motherName;
    String imagePath;
    String username;
    int id;
    int pincode;
    String laBdetails;
    int suborgwisedesgid;
    String perMobile;
    int avgPatient;
    String attchHospitalName;
    int isaspirant;
    String bloodgroup;
    int gplgdcode;
    DateTime dob;
    String bCompany;
    String workLocationName;
    String labIncharge;
    String projectName;
    String bankaddress;
    String liName;
    String liDocname;
    String pancard;
    String omtcscid;
    int yearofpassing;
    int centerId;
    String liContact;
    String designation;
    String maritialstatusId;
    String firstName;
    int educdtlid;
    bool interestinfranch;
    int desglevelid;
    String ifsccode;
    String spouseName;
    String religion;
    String labContact;
    int orgId;
    DateTime joiningdate;
    String fatherName;
    String aadhar;
    int tallgdcode;
    int mapDistCode;
    String ipaddress;
    int desgid;
    String bMobile;
    String cAddress;
    String bAddress;
    int percentage;
    String branchname;
    String maritialstatus;
    String liMobno;
    String typename;
    String pAddress;
    String cityName;
    String qualification;
    String centerName;
    String typeofsetup;
    String voterId;
    String edu;
    String district;
    String accountno;
    int typeid;
    String name;
    String lastName;
    String categoryId;
    int avgTest;
    String state;
    int statelgdcode;
    String labAddress;
    String universityname;
    int hlldistrictid;
    int facilityId;
    String perEmail;
    int subOrgId;
    int children;
    int age;
    String subOrgName;
    String bEmail;
    int patchCode;
    String projectId;
    int maplabCode;
    String middleName;
    int empCode;
    String labName;
    String taluka;
    String passbook;
    String bankname;
    int bloodid;
    String category;

    factory Output.fromJson(Map<dynamic, dynamic> json) => Output(
        cityCode: json["CityCode"],
        anniversarydate: json["anniversarydate"],
        worklocid: json["WORKLOCID"],
        patchName: json["PatchName"],
        orgName: json["OrgName"],
        gender: json["Gender"],
        facilityName: json["FacilityName"],
        bankid: json["BANKID"],
        cast: json["cast"],
        distlgdcode: json["DISTLGDCODE"],
        motherName: json["MotherName"],
        imagePath: json["ImagePath"],
        username: json["USERNAME"],
        id: json["ID"],
        pincode: json["pincode"],
        laBdetails: json["LABdetails"],
        suborgwisedesgid: json["SUBORGWISEDESGID"],
        perMobile: json["per_mobile"],
        avgPatient: json["AvgPatient"],
        attchHospitalName: json["ATTCH_HOSPITAL_NAME"],
        isaspirant: json["ISASPIRANT"],
        bloodgroup: json["bloodgroup"],
        gplgdcode: json["GPLGDCODE"],
        dob: DateTime.parse(json["dob"]),
        bCompany: json["BCompany"],
        workLocationName: json["WorkLocationName"],
        labIncharge: json["LabIncharge"],
        projectName: json["ProjectName"],
        bankaddress: json["bankaddress"],
        liName: json["LI_NAME"],
        liDocname: json["LI_DOCNAME"],
        pancard: json["pancard"],
        omtcscid: json["OMTCSCID"],
        yearofpassing: json["yearofpassing"],
        centerId: json["CenterID"],
        liContact: json["LI_CONTACT"],
        designation: json["Designation"],
        maritialstatusId: json["MaritialstatusId"],
        firstName: json["FirstName"],
        educdtlid: json["EDUCDTLID"],
        interestinfranch: json["INTERESTINFRANCH"],
        desglevelid: json["DESGLEVELID"],
        ifsccode: json["ifsccode"],
        spouseName: json["SpouseName"],
        religion: json["religion"],
        labContact: json["LAB_CONTACT"],
        orgId: json["OrgId"],
        joiningdate: DateTime.parse(json["joiningdate"]),
        fatherName: json["FatherName"],
        aadhar: json["Aadhar"],
        tallgdcode: json["TALLGDCODE"],
        mapDistCode: json["MapDISTCode"],
        ipaddress: json["IPADDRESS"],
        desgid: json["DESGID"],
        bMobile: json["BMobile"],
        cAddress: json["CAddress"],
        bAddress: json["BAddress"],
        percentage: json["percentage"],
        branchname: json["branchname"],
        maritialstatus: json["Maritialstatus"],
        liMobno: json["LI_MOBNO"],
        typename: json["TYPENAME"],
        pAddress: json["PAddress"],
        cityName: json["CityName"],
        qualification: json["qualification"],
        centerName: json["CenterName"],
        typeofsetup: json["TYPEOFSETUP"],
        voterId: json["VoterId"],
        edu: json["edu"],
        district: json["district"],
        accountno: json["accountno"],
        typeid: json["TYPEID"],
        name: json["name"],
        lastName: json["LastName"],
        categoryId: json["CategoryId"],
        avgTest: json["AvgTest"],
        state: json["STATE"],
        statelgdcode: json["STATELGDCODE"],
        labAddress: json["LABAddress"],
        universityname: json["universityname"],
        hlldistrictid: json["HLLDISTRICTID"],
        facilityId: json["FacilityID"],
        perEmail: json["per_email"],
        subOrgId: json["SubOrgId"],
        children: json["Children"],
        age: json["AGE"],
        subOrgName: json["SubOrgName"],
        bEmail: json["BEmail"],
        patchCode: json["PatchCode"],
        projectId: json["ProjectId"],
        maplabCode: json["MaplabCode"],
        middleName: json["MiddleName"],
        empCode: json["EmpCode"],
        labName: json["LabName"],
        taluka: json["taluka"],
        passbook: json["passbook"],
        bankname: json["bankname"],
        bloodid: json["BLOODID"],
        category: json["category"],
    );

    Map<dynamic, dynamic> toJson() => {
        "CityCode": cityCode,
        "anniversarydate": anniversarydate,
        "WORKLOCID": worklocid,
        "PatchName": patchName,
        "OrgName": orgName,
        "Gender": gender,
        "FacilityName": facilityName,
        "BANKID": bankid,
        "cast": cast,
        "DISTLGDCODE": distlgdcode,
        "MotherName": motherName,
        "ImagePath": imagePath,
        "USERNAME": username,
        "ID": id,
        "pincode": pincode,
        "LABdetails": laBdetails,
        "SUBORGWISEDESGID": suborgwisedesgid,
        "per_mobile": perMobile,
        "AvgPatient": avgPatient,
        "ATTCH_HOSPITAL_NAME": attchHospitalName,
        "ISASPIRANT": isaspirant,
        "bloodgroup": bloodgroup,
        "GPLGDCODE": gplgdcode,
        "dob": "${dob.year.toString().padLeft(4, '0')}-${dob.month.toString().padLeft(2, '0')}-${dob.day.toString().padLeft(2, '0')}",
        "BCompany": bCompany,
        "WorkLocationName": workLocationName,
        "LabIncharge": labIncharge,
        "ProjectName": projectName,
        "bankaddress": bankaddress,
        "LI_NAME": liName,
        "LI_DOCNAME": liDocname,
        "pancard": pancard,
        "OMTCSCID": omtcscid,
        "yearofpassing": yearofpassing,
        "CenterID": centerId,
        "LI_CONTACT": liContact,
        "Designation": designation,
        "MaritialstatusId": maritialstatusId,
        "FirstName": firstName,
        "EDUCDTLID": educdtlid,
        "INTERESTINFRANCH": interestinfranch,
        "DESGLEVELID": desglevelid,
        "ifsccode": ifsccode,
        "SpouseName": spouseName,
        "religion": religion,
        "LAB_CONTACT": labContact,
        "OrgId": orgId,
        "joiningdate": "${joiningdate.year.toString().padLeft(4, '0')}-${joiningdate.month.toString().padLeft(2, '0')}-${joiningdate.day.toString().padLeft(2, '0')}",
        "FatherName": fatherName,
        "Aadhar": aadhar,
        "TALLGDCODE": tallgdcode,
        "MapDISTCode": mapDistCode,
        "IPADDRESS": ipaddress,
        "DESGID": desgid,
        "BMobile": bMobile,
        "CAddress": cAddress,
        "BAddress": bAddress,
        "percentage": percentage,
        "branchname": branchname,
        "Maritialstatus": maritialstatus,
        "LI_MOBNO": liMobno,
        "TYPENAME": typename,
        "PAddress": pAddress,
        "CityName": cityName,
        "qualification": qualification,
        "CenterName": centerName,
        "TYPEOFSETUP": typeofsetup,
        "VoterId": voterId,
        "edu": edu,
        "district": district,
        "accountno": accountno,
        "TYPEID": typeid,
        "name": name,
        "LastName": lastName,
        "CategoryId": categoryId,
        "AvgTest": avgTest,
        "STATE": state,
        "STATELGDCODE": statelgdcode,
        "LABAddress": labAddress,
        "universityname": universityname,
        "HLLDISTRICTID": hlldistrictid,
        "FacilityID": facilityId,
        "per_email": perEmail,
        "SubOrgId": subOrgId,
        "Children": children,
        "AGE": age,
        "SubOrgName": subOrgName,
        "BEmail": bEmail,
        "PatchCode": patchCode,
        "ProjectId": projectId,
        "MaplabCode": maplabCode,
        "MiddleName": middleName,
        "EmpCode": empCode,
        "LabName": labName,
        "taluka": taluka,
        "passbook": passbook,
        "bankname": bankname,
        "BLOODID": bloodid,
        "category": category,
    };
}
